# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Ain't no love in the Jungle, ain't no, no, no!"
  displayName: 'Fred Again!'

- script: |
    echo "See: https://www.youtube.com/watch?v=zBp7KBmgsdU"
  displayName: 'You Tube Link'
